project:
  type: website
  output-dir: docs

website:
  title: "In and Out of Scope"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/WillGiang
      - icon: twitter
        href: https://twitter.com/MixIndentations
  google-analytics: "UA-110782240"
  open-graph: true
  twitter-card: true
  reader-mode: true
  page-footer: "Copyright 2022, William Giang"

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css