project:
  type: website
  output-dir: docs

website:
  title: "In and Out of Scope"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/WillGiang
      - icon: twitter
        href: https://twitter.com/MixIndentations
      - icon: rss
        href: index.xml
  cookie-consent:
    type: express
    style: headline
    pallete: dark
  image: DSM3-2-2_render.png
  google-analytics: "UA-110782240"
  open-graph: true
  twitter-card:
    creator: "@MixIndentations"
  reader-mode: true
  page-footer: "Copyright 2023, William Giang"
  site-url: "https://willgiang.github.io"

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css