project:
  type: website
  output-dir: docs

website:
  title: "In and Out of Scope"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/WillGiang
      - icon: twitter
        href: https://twitter.com/MixIndentations
format:
  html:
    theme: darkly
    css: styles.css



